// export const measurementPoints = [
//   // Top Panel Measurements
//   {
//     no: 1,
//     panel: "Top",
//     pointName: "Front left Body Length",
//     pointNameEng: "Front left Body Length",
//     pointNameKhmer: "សំរុងខ្លួនមុខខាងឆ្វេង",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Left",
//     measurementSide: "Length",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 2,
//     panel: "Top",
//     pointName: "Front left Chest Width",
//     pointNameEng: "Front left Chest Width",
//     pointNameKhmer: "ទំហំទ្រូងមុខខាងឆ្វេង",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Left",
//     measurementSide: "Width",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 3,
//     panel: "Top",
//     pointName: "Front Right Body Length",
//     pointNameEng: "Front Right Body Length",
//     pointNameKhmer: "សំរុងខ្លួនមុខខាងស្តាំ",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 4,
//     panel: "Top",
//     pointName: "Front Right Chest Width",
//     pointNameEng: "Front Right Chest Width",
//     pointNameKhmer: "ទំហំទ្រូងផ្ទាំងមុខខាងស្តាំ",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 5,
//     panel: "Top",
//     pointName: "Back Body Length",
//     pointNameEng: "Back Body Length",
//     pointNameKhmer: "សំរុងក្រោយ",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 6,
//     panel: "Top",
//     pointName: "Back Chest Width",
//     pointNameEng: "Back Chest Width",
//     pointNameKhmer: "ទំហំទ្រូងផ្ទាំងក្រោយ",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 7,
//     panel: "Top",
//     pointName: "Left Sleeve Length",
//     pointNameEng: "Left Sleeve Length",
//     pointNameKhmer: "ប្រវែងដៃខាងឆ្វេង",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Left",
//     measurementSide: "Length",
//     panelIndex: 3,
//     panelIndexName: "Left Sleeve",
//     panelIndexNameKhmer: "ដៃឆ្វេង"
//   },
//   {
//     no: 8,
//     panel: "Top",
//     pointName: "Left Bicep Width",
//     pointNameEng: "Left Bicep Width",
//     pointNameKhmer: "ទំហំកំភួនដៃខាងឆ្វេង",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Left",
//     measurementSide: "Width",
//     panelIndex: 3,
//     panelIndexName: "Left Sleeve",
//     panelIndexNameKhmer: "ដៃឆ្វេង"
//   },
//   {
//     no: 9,
//     panel: "Top",
//     pointName: "Right Sleeve Length",
//     pointNameEng: "Right Sleeve Length",
//     pointNameKhmer: "ប្រវែងដៃខាងស្តាំ",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 4,
//     panelIndexName: "Right Sleeve",
//     panelIndexNameKhmer: "ដៃស្តាំ"
//   },
//   {
//     no: 10,
//     panel: "Top",
//     pointName: "Right Bicep Width",
//     pointNameEng: "Right Bicep Width",
//     pointNameKhmer: "ទំហំកំភួនដៃខាងស្តាំ",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 4,
//     panelIndexName: "Right Sleeve",
//     panelIndexNameKhmer: "ដៃស្តាំ"
//   },
//   {
//     no: 11,
//     panel: "Top",
//     pointName: "Neck band length",
//     pointNameEng: "Neck band length",
//     pointNameKhmer: "ប្រវែងសន្លឹកករ",
//     panelName: "Other",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 5,
//     panelIndexName: "Other",
//     panelIndexNameKhmer: "ផ្សេងទៀត"
//   },
//   {
//     no: 12,
//     panel: "Top",
//     pointName: "Neck band height",
//     pointNameEng: "Neck band height",
//     pointNameKhmer: "ទំហំសន្លឹកករ",
//     panelName: "Other",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 5,
//     panelIndexName: "Other",
//     panelIndexNameKhmer: "ផ្សេងទៀត"
//   },

//   // Top Hoodies Panel Measurements
//   {
//     no: 13,
//     panel: "Zipper Jacket",
//     pointName: "Front Body Length",
//     pointNameEng: "Front Body Length",
//     pointNameKhmer: "សំរុងខ្លួនផ្ទាំងមុខ",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },

//   {
//     no: 14,
//     panel: "Zipper Jacket",
//     pointName: "Front Chest Width",
//     pointNameEng: "Front Chest Width",
//     pointNameKhmer: "ទំហំទ្រូងមុខ",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },

//   {
//     no: 15,
//     panel: "Zipper Jacket",
//     pointName: "Back Body Length",
//     pointNameEng: "Back Body Length",
//     pointNameKhmer: "សំរុងផ្ទាំងក្រោយ",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },

//   {
//     no: 16,
//     panel: "Zipper Jacket",
//     pointName: "Back Chest Width",
//     pointNameEng: "Back Chest Width",
//     pointNameKhmer: "ទំហំទ្រូងផ្ទាំងក្រោយ",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 17,
//     panel: "Zipper Jacket",
//     pointName: "Left Sleeve Length",
//     pointNameEng: "Left Sleeve Length",
//     pointNameKhmer: "ប្រវែងដៃខាងឆ្វេង",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Left",
//     measurementSide: "Length",
//     panelIndex: 3,
//     panelIndexName: "Left Sleeve",
//     panelIndexNameKhmer: "ដៃឆ្វេង"
//   },
//   {
//     no: 18,
//     panel: "Zipper Jacket",
//     pointName: "Left Bicep Width",
//     pointNameEng: "Left Bicep Width",
//     pointNameKhmer: "ទំហំកំភួនដៃខាងឆ្វេង",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Left",
//     measurementSide: "Width",
//     panelIndex: 3,
//     panelIndexName: "Left Sleeve",
//     panelIndexNameKhmer: "ដៃឆ្វេង"
//   },
//   {
//     no: 19,
//     panel: "Zipper Jacket",
//     pointName: "Right Sleeve Length",
//     pointNameEng: "Right Sleeve Length",
//     pointNameKhmer: "ប្រវែងដៃខាងស្តាំ",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 4,
//     panelIndexName: "Right Sleeve",
//     panelIndexNameKhmer: "ដៃស្តាំ"
//   },
//   {
//     no: 20,
//     panel: "Zipper Jacket",
//     pointName: "Right Bicep Width",
//     pointNameEng: "Right Bicep Width",
//     pointNameKhmer: "ទំហំកំភួនដៃខាងស្តាំ",
//     panelName: "Sleeve",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 4,
//     panelIndexName: "Right Sleeve",
//     panelIndexNameKhmer: "ដៃស្តាំ"
//   },
//   {
//     no: 21,
//     panel: "Zipper Jacket",
//     pointName: "Pocket Length",
//     pointNameEng: "Pocket Length",
//     pointNameKhmer: "សំរុងហោប៉ៅ",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 5,
//     panelIndexName: "Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅ"
//   },
//   {
//     no: 22,
//     panel: "Zipper Jacket",
//     pointName: "Pocket Width",
//     pointNameEng: "Pocket Width",
//     pointNameKhmer: "ទំហំហោប៉ៅ",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 5,
//     panelIndexName: "Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅ"
//   },
//   {
//     no: 23,
//     panel: "Zipper Jacket",
//     pointName: "Hat Length",
//     pointNameEng: "Hat Length",
//     pointNameKhmer: "សំរុងមួក",
//     panelName: "Other",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 6,
//     panelIndexName: "Other",
//     panelIndexNameKhmer: "ផ្សេងទៀត"
//   },
//   {
//     no: 24,
//     panel: "Zipper Jacket",
//     pointName: "Hat width",
//     pointNameEng: "Hat width",
//     pointNameKhmer: "ទំហំមួក",
//     panelName: "Other",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 6,
//     panelIndexName: "Other",
//     panelIndexNameKhmer: "ផ្សេងទៀត"
//   },

//   // Bottom Panel Measurements
//   {
//     no: 25,
//     panel: "Bottom",
//     pointName: "Front Left Length",
//     pointNameEng: "Front Left Length",
//     pointNameKhmer: "ប្រវែងជើងឆ្វេង(មុខ)",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Left",
//     measurementSide: "Length",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 26,
//     panel: "Bottom",
//     pointName: "Front Left Crotch Width",
//     pointNameEng: "Front Left Crotch Width",
//     pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថឆ្វេង(មុខ)",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Left",
//     measurementSide: "Width",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 27,
//     panel: "Bottom",
//     pointName: "Front Right Length",
//     pointNameEng: "Front Right Length",
//     pointNameKhmer: "ប្រវែងជើងស្តាំ(មុខ)",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 28,
//     panel: "Bottom",
//     pointName: "Front Right Crotch Width",
//     pointNameEng: "Front Right Crotch Width",
//     pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថស្តាំ(មុខ)",
//     panelName: "Body",
//     panelSide: "Front",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 1,
//     panelIndexName: "Front Body",
//     panelIndexNameKhmer: "ផ្ទាំងមុខ"
//   },
//   {
//     no: 29,
//     panel: "Bottom",
//     pointName: "Back Left Length",
//     pointNameEng: "Back Left Length",
//     pointNameKhmer: "ប្រវែងជើងឆ្វេង(ក្រោយ)",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "Left",
//     measurementSide: "Length",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 30,
//     panel: "Bottom",
//     pointName: "Back Left Crotch Width",
//     pointNameEng: "Back Left Crotch Width",
//     pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថឆ្វេង(ក្រោយ)",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "Left",
//     measurementSide: "Width",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 31,
//     panel: "Bottom",
//     pointName: "Back Right Length",
//     pointNameEng: "Back Right Length",
//     pointNameKhmer: "ប្រវែងជើងស្តាំ(ក្រោយ)",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 32,
//     panel: "Bottom",
//     pointName: "Back Right Crotch Width",
//     pointNameEng: "Back Right Crotch Width",
//     pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថស្តាំ(ក្រោយ)",
//     panelName: "Body",
//     panelSide: "Back",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 2,
//     panelIndexName: "Back Body",
//     panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
//   },
//   {
//     no: 33,
//     panel: "Bottom",
//     pointName: "Pocket part Length",
//     pointNameEng: "Pocket part Length",
//     pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅឆ្វេង",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Length",
//     panelIndex: 3,
//     panelIndexName: "Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅឆ្វេង"
//   },
//   {
//     no: 34,
//     panel: "Bottom",
//     pointName: "Pocket part Width",
//     pointNameEng: "Pocket part Width",
//     pointNameKhmer: "ទំហំសន្ទះហោប៉ៅឆ្វេង",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "NA",
//     measurementSide: "Width",
//     panelIndex: 3,
//     panelIndexName: "Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅឆ្វេង"
//   },
//   {
//     no: 35,
//     panel: "Bottom",
//     pointName: "Right pocket part length",
//     pointNameEng: "Right pocket part length",
//     pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅស្តាំ",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Length",
//     panelIndex: 4,
//     panelIndexName: "Right Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅស្តាំ"
//   },
//   {
//     no: 36,
//     panel: "Bottom",
//     pointName: "Right pocket part width",
//     pointNameEng: "Right pocket part width",
//     pointNameKhmer: "ទំហំសន្ទះហោប៉ៅ",
//     panelName: "Pocket",
//     panelSide: "NA",
//     panelDirection: "Right",
//     measurementSide: "Width",
//     panelIndex: 4,
//     panelIndexName: "Right Pocket",
//     panelIndexNameKhmer: "ហ៉ោប៉ៅស្តាំ"
//   }
// ];

export const measurementPoints = [
  // Top Panel Measurements
  {
    no: 1,
    panel: "Top",
    pointName: "Front Chest Width",
    pointNameEng: "Front Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 2,
    panel: "Top",
    pointName: "Front Body Length",
    pointNameEng: "Front Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 3,
    panel: "Top",
    pointName: "Back Chest Width",
    pointNameEng: "Back Chest Width",
    pointNameKhmer: "ទំហំទ្រូងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 4,
    panel: "Top",
    pointName: "Back Body Length",
    pointNameEng: "Back Body Length",
    pointNameKhmer: "សំរុងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 5,
    panel: "Top",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 6,
    panel: "Top",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 7,
    panel: "Top",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 8,
    panel: "Top",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 9,
    panel: "Top",
    pointName: "Hat Width",
    pointNameEng: "Hat Width",
    pointNameKhmer: "ទំហំមួក",
    panelName: "Hat",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Hat",
    panelIndexNameKhmer: "មួក"
  },
  {
    no: 10,
    panel: "Top",
    pointName: "Hat Length",
    pointNameEng: "Hat Length",
    pointNameKhmer: "សំរុងមួក",
    panelName: "Hat",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Hat",
    panelIndexNameKhmer: "មួក"
  },
  {
    no: 11,
    panel: "Top",
    pointName: "Pocket Width",
    pointNameEng: "Pocket Width",
    pointNameKhmer: "ទំហំហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 6,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  },
  {
    no: 12,
    panel: "Top",
    pointName: "Pocket Length",
    pointNameEng: "Pocket Length",
    pointNameKhmer: "សំរុងហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 6,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  },

  // Zipper Jacket Panel Measurements
  {
    no: 13,
    panel: "Zipper Jacket",
    pointName: "Front Left Chest Width",
    pointNameEng: "Front Left Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខឆ្វេង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Left",
    panelIndexNameKhmer: "មុខឆ្វេង"
  },
  {
    no: 14,
    panel: "Zipper Jacket",
    pointName: "Front Left Body Length",
    pointNameEng: "Front Left Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខឆ្វេង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Left",
    panelIndexNameKhmer: "មុខឆ្វេង"
  },
  {
    no: 15,
    panel: "Zipper Jacket",
    pointName: "Front Right Chest Width",
    pointNameEng: "Front Right Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខស្តាំ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Front Right",
    panelIndexNameKhmer: "មុខស្តាំ"
  },
  {
    no: 16,
    panel: "Zipper Jacket",
    pointName: "Front Right Body Length",
    pointNameEng: "Front Right Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខស្តាំ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Front Right",
    panelIndexNameKhmer: "មុខស្តាំ"
  },
  {
    no: 17,
    panel: "Zipper Jacket",
    pointName: "Back Chest Width",
    pointNameEng: "Back Chest Width",
    pointNameKhmer: "ទំហំទ្រូងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 18,
    panel: "Zipper Jacket",
    pointName: "Back Body Length",
    pointNameEng: "Back Body Length",
    pointNameKhmer: "សំរុងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 19,
    panel: "Zipper Jacket",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 20,
    panel: "Zipper Jacket",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 21,
    panel: "Zipper Jacket",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 22,
    panel: "Zipper Jacket",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 23,
    panel: "Zipper Jacket",
    pointName: "Neck Band Height",
    pointNameEng: "Neck Band Height",
    pointNameKhmer: "ទំហំសន្លឹកករ",
    panelName: "Neck Band",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 6,
    panelIndexName: "Neck Band",
    panelIndexNameKhmer: "សន្លឹកករ"
  },
  {
    no: 24,
    panel: "Zipper Jacket",
    pointName: "Neck Band Length",
    pointNameEng: "Neck Band Length",
    pointNameKhmer: "ប្រវែងសន្លឹកករ",
    panelName: "Neck Band",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 6,
    panelIndexName: "Neck Band",
    panelIndexNameKhmer: "សន្លឹកករ"
  },
  {
    no: 25,
    panel: "Zipper Jacket",
    pointName: "Hat Width",
    pointNameEng: "Hat Width",
    pointNameKhmer: "ទំហំមួក",
    panelName: "Hat",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 7,
    panelIndexName: "Hat",
    panelIndexNameKhmer: "មួក"
  },
  {
    no: 26,
    panel: "Zipper Jacket",
    pointName: "Hat Length",
    pointNameEng: "Hat Length",
    pointNameKhmer: "សំរុងមួក",
    panelName: "Hat",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 7,
    panelIndexName: "Hat",
    panelIndexNameKhmer: "មួក"
  },

  // Bottom Panel Measurements
  {
    no: 27,
    panel: "Bottom",
    pointName: "Front Left Crotch Width",
    pointNameEng: "Front Left Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅចុងគូថឆ្វេងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Left Crotch",
    panelIndexNameKhmer: "គូថឆ្វេង"
  },
  {
    no: 28,
    panel: "Bottom",
    pointName: "Front Left Length",
    pointNameEng: "Front Left Length",
    pointNameKhmer: "ប្រវែងជើងឆ្វេងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 29,
    panel: "Bottom",
    pointName: "Back Left Crotch Width",
    pointNameEng: "Back Left Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅចុងគូថឆ្វេងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Left Crotch",
    panelIndexNameKhmer: "គូថឆ្វេង"
  },
  {
    no: 30,
    panel: "Bottom",
    pointName: "Back Left Length",
    pointNameEng: "Back Left Length",
    pointNameKhmer: "ប្រវែងជើងឆ្វេងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Back Left",
    panelIndexNameKhmer: "ក្រោយឆ្វេង"
  },
  {
    no: 31,
    panel: "Bottom",
    pointName: "Front Right Crotch Width",
    pointNameEng: "Front Right Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅចុងគូថស្តាំមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Crotch",
    panelIndexNameKhmer: "គូថស្តាំ"
  },
  {
    no: 32,
    panel: "Bottom",
    pointName: "Front Right Length",
    pointNameEng: "Front Right Length",
    pointNameKhmer: "ប្រវែងជើងស្តាំមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Front Right",
    panelIndexNameKhmer: "មុខស្តាំ"
  },
  {
    no: 33,
    panel: "Bottom",
    pointName: "Back Right Crotch Width",
    pointNameEng: "Back Right Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅចុងគូថស្តាំក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Crotch",
    panelIndexNameKhmer: "គូថស្តាំ"
  },
  {
    no: 34,
    panel: "Bottom",
    pointName: "Back Right Length",
    pointNameEng: "Back Right Length",
    pointNameKhmer: "ប្រវែងជើងស្តាំក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 6,
    panelIndexName: "Back Right",
    panelIndexNameKhmer: "ក្រោយស្តាំ"
  },
  {
    no: 35,
    panel: "Bottom",
    pointName: "Left Pocket Part Width",
    pointNameEng: "Left Pocket Part Width",
    pointNameKhmer: "ទំហំសន្ទះហោប៉ៅឆ្វេង",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 7,
    panelIndexName: "Pocket Left",
    panelIndexNameKhmer: "ហោប៉ៅឆ្វេង"
  },
  {
    no: 36,
    panel: "Bottom",
    pointName: "Left Pocket Part Length",
    pointNameEng: "Left Pocket Part Length",
    pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅឆ្វេង",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 7,
    panelIndexName: "Pocket Left",
    panelIndexNameKhmer: "ហោប៉ៅឆ្វេង"
  },
  {
    no: 37,
    panel: "Bottom",
    pointName: "Right Pocket Part Width",
    pointNameEng: "Right Pocket Part Width",
    pointNameKhmer: "ទំហំសន្ទះហោប៉ៅស្តាំ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 8,
    panelIndexName: "Pocket Right",
    panelIndexNameKhmer: "ហោប៉ៅស្តាំ"
  },
  {
    no: 38,
    panel: "Bottom",
    pointName: "Right Pocket Part Length",
    pointNameEng: "Right Pocket Part Length",
    pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅស្តាំ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 8,
    panelIndexName: "Pocket Right",
    panelIndexNameKhmer: "ហោប៉ៅស្តាំ"
  },
  {
    no: 39,
    panel: "Bottom",
    pointName: "Waistband Width",
    pointNameEng: "Waistband Width",
    pointNameKhmer: "ទំហំចង្កេះ",
    panelName: "Waistband",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 9,
    panelIndexName: "Waistband",
    panelIndexNameKhmer: "ចង្កេះ"
  },
  {
    no: 40,
    panel: "Bottom",
    pointName: "Waistband Length",
    pointNameEng: "Waistband Length",
    pointNameKhmer: "ប្រវែងចង្កេះ",
    panelName: "Waistband",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 9,
    panelIndexName: "Waistband",
    panelIndexNameKhmer: "ចង្កេះ"
  },

  // Top Layer Panel Measurements
  {
    no: 41,
    panel: "Top Layer",
    pointName: "Front Chest Width Inner",
    pointNameEng: "Front Chest Width Inner",
    pointNameKhmer: "ទំហំទ្រូងមុខក្នុង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 42,
    panel: "Top Layer",
    pointName: "Front Chest Width Outer",
    pointNameEng: "Front Chest Width Outer",
    pointNameKhmer: "ទំហំទ្រូងមុខក្រៅ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 43,
    panel: "Top Layer",
    pointName: "Front Body Length Inner",
    pointNameEng: "Front Body Length Inner",
    pointNameKhmer: "សំរុងខ្លួនមុខក្នុង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 44,
    panel: "Top Layer",
    pointName: "Front Body Length Outer",
    pointNameEng: "Front Body Length Outer",
    pointNameKhmer: "សំរុងខ្លួនមុខក្រៅ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 45,
    panel: "Top Layer",
    pointName: "Back Chest Width Inner",
    pointNameEng: "Back Chest Width Inner",
    pointNameKhmer: "ទំហំទ្រូងក្រោយក្នុង",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 46,
    panel: "Top Layer",
    pointName: "Back Chest Width Outer",
    pointNameEng: "Back Chest Width Outer",
    pointNameKhmer: "ទំហំទ្រូងក្រោយក្រៅ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 47,
    panel: "Top Layer",
    pointName: "Back Body Length Inner",
    pointNameEng: "Back Body Length Inner",
    pointNameKhmer: "សំរុងក្រោយក្នុង",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 48,
    panel: "Top Layer",
    pointName: "Back Body Length Outer",
    pointNameEng: "Back Body Length Outer",
    pointNameKhmer: "សំរុងក្រោយក្រៅ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 49,
    panel: "Top Layer",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 50,
    panel: "Top Layer",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 51,
    panel: "Top Layer",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 52,
    panel: "Top Layer",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 53,
    panel: "Top Layer",
    pointName: "Pocket Width",
    pointNameEng: "Pocket Width",
    pointNameKhmer: "ទំហំហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  },
  {
    no: 54,
    panel: "Top Layer",
    pointName: "Pocket Length",
    pointNameEng: "Pocket Length",
    pointNameKhmer: "សំរុងហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  },
  {
    no: 55,
    panel: "Top Layer",
    pointName: "Waistband Length",
    pointNameEng: "Waistband Length",
    pointNameKhmer: "ប្រវែងចង្កេះ",
    panelName: "Waistband",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 6,
    panelIndexName: "Waistband",
    panelIndexNameKhmer: "ចង្កេះ"
  },
  {
    no: 56,
    panel: "Top Layer",
    pointName: "Waistband Width",
    pointNameEng: "Waistband Width",
    pointNameKhmer: "ទំហំចង្កេះ",
    panelName: "Waistband",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 6,
    panelIndexName: "Waistband",
    panelIndexNameKhmer: "ចង្កេះ"
  },

  // Dress Panel Measurements
  {
    no: 57,
    panel: "Dress",
    pointName: "Front Chest Width",
    pointNameEng: "Front Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 58,
    panel: "Dress",
    pointName: "Front Body Length",
    pointNameEng: "Front Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front",
    panelIndexNameKhmer: "មុខ"
  },
  {
    no: 59,
    panel: "Dress",
    pointName: "Back Chest Width",
    pointNameEng: "Back Chest Width",
    pointNameKhmer: "ទំហំទ្រូងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 60,
    panel: "Dress",
    pointName: "Back Body Length",
    pointNameEng: "Back Body Length",
    pointNameKhmer: "សំរុងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back",
    panelIndexNameKhmer: "ក្រោយ"
  },
  {
    no: 61,
    panel: "Dress",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 62,
    panel: "Dress",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 63,
    panel: "Dress",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 64,
    panel: "Dress",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 65,
    panel: "Dress",
    pointName: "Pocket Length",
    pointNameEng: "Pocket Length",
    pointNameKhmer: "សំរុងហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  },
  {
    no: 66,
    panel: "Dress",
    pointName: "Pocket Width",
    pointNameEng: "Pocket Width",
    pointNameKhmer: "ទំហំហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហោប៉ៅ"
  }
];
