export const measurementPoints = [
  // Top Panel Measurements
  {
    no: 1,
    panel: "Top",
    pointName: "Front left Body Length",
    pointNameEng: "Front left Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខខាងឆ្វេង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 2,
    panel: "Top",
    pointName: "Front left Chest Width",
    pointNameEng: "Front left Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខខាងឆ្វេង",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 3,
    panel: "Top",
    pointName: "Front Right Body Length",
    pointNameEng: "Front Right Body Length",
    pointNameKhmer: "សំរុងខ្លួនមុខខាងស្តាំ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 4,
    panel: "Top",
    pointName: "Front Right Chest Width",
    pointNameEng: "Front Right Chest Width",
    pointNameKhmer: "ទំហំទ្រូងផ្ទាំងមុខខាងស្តាំ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 5,
    panel: "Top",
    pointName: "Back Body Length",
    pointNameEng: "Back Body Length",
    pointNameKhmer: "សំរុងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 6,
    panel: "Top",
    pointName: "Back Chest Width",
    pointNameEng: "Back Chest Width",
    pointNameKhmer: "ទំហំទ្រូងផ្ទាំងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 7,
    panel: "Top",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃខាងឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 8,
    panel: "Top",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃខាងឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 9,
    panel: "Top",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃខាងស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 10,
    panel: "Top",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃខាងស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 11,
    panel: "Top",
    pointName: "Neck band length",
    pointNameEng: "Neck band length",
    pointNameKhmer: "ប្រវែងសន្លឹកករ",
    panelName: "Other",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Other",
    panelIndexNameKhmer: "ផ្សេងទៀត"
  },
  {
    no: 12,
    panel: "Top",
    pointName: "Neck band height",
    pointNameEng: "Neck band height",
    pointNameKhmer: "ទំហំសន្លឹកករ",
    panelName: "Other",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Other",
    panelIndexNameKhmer: "ផ្សេងទៀត"
  },

  // Top Hoodies Panel Measurements
  {
    no: 13,
    panel: "Top Hoodies",
    pointName: "Front Body Length",
    pointNameEng: "Front Body Length",
    pointNameKhmer: "សំរុងខ្លួនផ្ទាំងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },

  {
    no: 14,
    panel: "Top Hoodies",
    pointName: "Front Chest Width",
    pointNameEng: "Front Chest Width",
    pointNameKhmer: "ទំហំទ្រូងមុខ",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },

  {
    no: 15,
    panel: "Top Hoodies",
    pointName: "Back Body Length",
    pointNameEng: "Back Body Length",
    pointNameKhmer: "សំរុងផ្ទាំងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },

  {
    no: 16,
    panel: "Top Hoodies",
    pointName: "Back Chest Width",
    pointNameEng: "Back Chest Width",
    pointNameKhmer: "ទំហំទ្រូងផ្ទាំងក្រោយ",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 17,
    panel: "Top Hoodies",
    pointName: "Left Sleeve Length",
    pointNameEng: "Left Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃខាងឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 18,
    panel: "Top Hoodies",
    pointName: "Left Bicep Width",
    pointNameEng: "Left Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃខាងឆ្វេង",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Left Sleeve",
    panelIndexNameKhmer: "ដៃឆ្វេង"
  },
  {
    no: 19,
    panel: "Top Hoodies",
    pointName: "Right Sleeve Length",
    pointNameEng: "Right Sleeve Length",
    pointNameKhmer: "ប្រវែងដៃខាងស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 20,
    panel: "Top Hoodies",
    pointName: "Right Bicep Width",
    pointNameEng: "Right Bicep Width",
    pointNameKhmer: "ទំហំកំភួនដៃខាងស្តាំ",
    panelName: "Sleeve",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Sleeve",
    panelIndexNameKhmer: "ដៃស្តាំ"
  },
  {
    no: 21,
    panel: "Top Hoodies",
    pointName: "Pocket Length",
    pointNameEng: "Pocket Length",
    pointNameKhmer: "សំរុងហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅ"
  },
  {
    no: 22,
    panel: "Top Hoodies",
    pointName: "Pocket Width",
    pointNameEng: "Pocket Width",
    pointNameKhmer: "ទំហំហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 5,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅ"
  },
  {
    no: 23,
    panel: "Top Hoodies",
    pointName: "Hat Length",
    pointNameEng: "Hat Length",
    pointNameKhmer: "សំរុងមួក",
    panelName: "Other",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 6,
    panelIndexName: "Other",
    panelIndexNameKhmer: "ផ្សេងទៀត"
  },
  {
    no: 24,
    panel: "Top Hoodies",
    pointName: "Hat width",
    pointNameEng: "Hat width",
    pointNameKhmer: "ទំហំមួក",
    panelName: "Other",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 6,
    panelIndexName: "Other",
    panelIndexNameKhmer: "ផ្សេងទៀត"
  },

  // Bottom Panel Measurements
  {
    no: 25,
    panel: "Bottom",
    pointName: "Front Left Length",
    pointNameEng: "Front Left Length",
    pointNameKhmer: "ប្រវែងជើងឆ្វេង(មុខ)",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 26,
    panel: "Bottom",
    pointName: "Front Left Crotch Width",
    pointNameEng: "Front Left Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថឆ្វេង(មុខ)",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 27,
    panel: "Bottom",
    pointName: "Front Right Length",
    pointNameEng: "Front Right Length",
    pointNameKhmer: "ប្រវែងជើងស្តាំ(មុខ)",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 28,
    panel: "Bottom",
    pointName: "Front Right Crotch Width",
    pointNameEng: "Front Right Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថស្តាំ(មុខ)",
    panelName: "Body",
    panelSide: "Front",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 1,
    panelIndexName: "Front Body",
    panelIndexNameKhmer: "ផ្ទាំងមុខ"
  },
  {
    no: 29,
    panel: "Bottom",
    pointName: "Back Left Length",
    pointNameEng: "Back Left Length",
    pointNameKhmer: "ប្រវែងជើងឆ្វេង(ក្រោយ)",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Left",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 30,
    panel: "Bottom",
    pointName: "Back Left Crotch Width",
    pointNameEng: "Back Left Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថឆ្វេង(ក្រោយ)",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Left",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 31,
    panel: "Bottom",
    pointName: "Back Right Length",
    pointNameEng: "Back Right Length",
    pointNameKhmer: "ប្រវែងជើងស្តាំ(ក្រោយ)",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 32,
    panel: "Bottom",
    pointName: "Back Right Crotch Width",
    pointNameEng: "Back Right Crotch Width",
    pointNameKhmer: "ទំហំភ្លៅនៅចុងគូថស្តាំ(ក្រោយ)",
    panelName: "Body",
    panelSide: "Back",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 2,
    panelIndexName: "Back Body",
    panelIndexNameKhmer: "ផ្ទាំងក្រោយ"
  },
  {
    no: 33,
    panel: "Bottom",
    pointName: "Pocket part Length",
    pointNameEng: "Pocket part Length",
    pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅឆ្វេង",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Length",
    panelIndex: 3,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅឆ្វេង"
  },
  {
    no: 34,
    panel: "Bottom",
    pointName: "Pocket part Width",
    pointNameEng: "Pocket part Width",
    pointNameKhmer: "ទំហំសន្ទះហោប៉ៅឆ្វេង",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "NA",
    measurementSide: "Width",
    panelIndex: 3,
    panelIndexName: "Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅឆ្វេង"
  },
  {
    no: 35,
    panel: "Bottom",
    pointName: "Right pocket part length",
    pointNameEng: "Right pocket part length",
    pointNameKhmer: "ប្រវែងសន្ទះហោប៉ៅស្តាំ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Length",
    panelIndex: 4,
    panelIndexName: "Right Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅស្តាំ"
  },
  {
    no: 36,
    panel: "Bottom",
    pointName: "Right pocket part width",
    pointNameEng: "Right pocket part width",
    pointNameKhmer: "ទំហំសន្ទះហោប៉ៅ",
    panelName: "Pocket",
    panelSide: "NA",
    panelDirection: "Right",
    measurementSide: "Width",
    panelIndex: 4,
    panelIndexName: "Right Pocket",
    panelIndexNameKhmer: "ហ៉ោប៉ៅស្តាំ"
  }
];
